---
- hosts: wordpress
  vars:
    http_port: 80
    max_clients: 200
  remote_user: ec2-user
  tasks:
  - name: Sets the owner of /var/www/html to be apache
    file: group=apache owner=apache path=/var/www/ recurse=yes state=touch
    become: yes
    become_user: root
