---
- hosts: wordpress
  vars:
    http_port: 80
    max_clients: 200
  remote_user: ec2-user
  tasks:
  - name: stops crond
    service: name=crond state=started enabled=yes
    become: yes
    become_user: root
